inherit_from: .rubocop_todo.yml

Style/NumericPredicate:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'spec/code_object_spec.rb'
    - 'lib/pry/method.rb'
    - 'lib/pry/wrapped_module.rb'
    - 'lib/pry/code.rb'
