class Pry
  class Command::TogglePryDeprecations < Pry::ClassCommand
    match 'toggle-pry-deprecations'
    group 'Misc'
    description 'Toggle the printing of deprecation messages for this Pry session.'

    banner <<-'BANNER'
      Usage: toggle-pry-deprecations

      Toggle the printing of deprecation messages for this Pry session.

      The toggle applies to deprecation messages installed through Pry::Deprecate
      ('show-source Pry::Deprecate'), and not those generated by other libraries or
      Ruby itself.
    BANNER

    def process
      _pry_.config.print_deprecations = !_pry_.config.print_deprecations
      _pry_.pager.page(_pry_.config.print_deprecations ? on_message : off_message)
    end

    def on_message
      "#{_pry_.h.green("OK")} Pry is printing deprecation messages for this session.\n"
    end

    def off_message
      "#{_pry_.h.green("OK")} Pry is not printing deprecation messages for this session.\n"
    end

    Pry::Commands.add_command(self)
  end
end
