.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PRY" "1" "December 2012" "" ""
.
.SH "NAME"
\fBPRY\fR \- A Reference to the PRY repl\.
.
.SH "Synopsis"
#
.
.SH "DESCRIPTION"
Does stuff\.
.
.SH "HOMEPAGE"
Here are some places to look on the intrawebz
.
.SH "OPTIONS"
Here are some of my cool options
.
.SH "FILES"
Here are some places to look on your system
.
.SH "Pry Commands"
Some commands\.
.
.SH "EXAMPLES"
Look at me do stuff\.
.
.SH "AUTHORS"
Fred Flintstone
